23:19:43.558 Running build in Washington, D.C., USA (East) – iad1
23:19:43.559 Build machine configuration: 4 cores, 8 GB
23:19:43.664 Cloning github.com/manhgopatel5/airanh (Branch: main, Commit: e29023e)
23:19:43.934 Cloning completed: 269.000ms
23:19:44.754 Skipping build cache since Node.js version changed from "24.x" to "20.x"
23:19:44.969 Running "vercel build"
23:19:45.554 Vercel CLI 51.6.1
23:19:45.791 Warning: Due to "engines": { "node": "20.x" } in your `package.json` file, the Node.js Version defined in your Project Settings ("24.x") will not apply, Node.js Version "20.x" will be used instead. Learn More: https://vercel.link/node-version
23:19:45.843 Detected `pnpm-lock.yaml` version 9 generated by pnpm@10.x with package.json#packageManager pnpm@9.12.3
23:19:45.882 Installing dependencies...
23:19:47.804 Lockfile is up to date, resolution step is skipped
23:19:47.887 Progress: resolved 1, reused 0, downloaded 0, added 0
23:19:48.043 Packages: +917
23:19:48.043 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
23:19:48.888 Progress: resolved 917, reused 0, downloaded 27, added 14
23:19:49.889 Progress: resolved 917, reused 0, downloaded 66, added 59
23:19:50.890 Progress: resolved 917, reused 0, downloaded 74, added 64
23:19:51.891 Progress: resolved 917, reused 0, downloaded 88, added 73
23:19:52.892 Progress: resolved 917, reused 0, downloaded 104, added 87
23:19:53.893 Progress: resolved 917, reused 0, downloaded 119, added 101
23:19:54.893 Progress: resolved 917, reused 0, downloaded 139, added 129
23:19:55.893 Progress: resolved 917, reused 0, downloaded 225, added 212
23:19:56.896 Progress: resolved 917, reused 0, downloaded 392, added 384
23:19:57.897 Progress: resolved 917, reused 0, downloaded 580, added 573
23:19:58.898 Progress: resolved 917, reused 0, downloaded 789, added 788
23:19:59.411 Progress: resolved 917, reused 0, downloaded 917, added 917, done
23:19:59.703 .../sharp@0.34.5/node_modules/sharp install$ node install/check.js || npm run build
23:19:59.722 .../sharp@0.33.5/node_modules/sharp install$ node install/check
23:20:01.818 .../sharp@0.33.5/node_modules/sharp install: Done
23:20:01.821 .../sharp@0.34.5/node_modules/sharp install: Done
23:20:01.833 The following dependencies have build scripts that were ignored: @firebase/util, esbuild, protobufjs, unrs-resolver
23:20:02.038 
23:20:02.039 dependencies:
23:20:02.039 + @hookform/resolvers 3.10.0
23:20:02.039 + @vercel/analytics 2.0.1
23:20:02.039 + @vercel/speed-insights 2.0.0
23:20:02.039 + browser-image-compression 2.0.2
23:20:02.039 + clsx 2.1.1
23:20:02.039 + date-fns 4.1.0
23:20:02.039 + firebase 12.12.1
23:20:02.039 + framer-motion 11.18.2
23:20:02.039 + isomorphic-dompurify 3.9.0
23:20:02.039 + linkify-react 4.3.2
23:20:02.039 + lucide-react 0.453.0
23:20:02.039 + nanoid 5.1.9
23:20:02.039 + next 15.5.15
23:20:02.039 + next-themes 0.3.0
23:20:02.039 + react 18.3.1
23:20:02.039 + react-dom 18.3.1
23:20:02.039 + react-hook-form 7.73.1
23:20:02.039 + react-hot-toast 2.6.0
23:20:02.039 + react-icons 5.6.0
23:20:02.039 + sharp 0.33.5
23:20:02.039 + sonner 1.7.4
23:20:02.040 + tailwind-merge 2.6.1
23:20:02.040 + zod 3.25.76
23:20:02.040 + zustand 4.5.7
23:20:02.040 
23:20:02.040 devDependencies:
23:20:02.040 + @next/bundle-analyzer 15.5.15
23:20:02.040 + @playwright/test 1.59.1
23:20:02.040 + @tailwindcss/container-queries 0.1.1
23:20:02.040 + @tailwindcss/forms 0.5.11
23:20:02.040 + @tailwindcss/typography 0.5.19
23:20:02.040 + @types/node 20.19.39
23:20:02.040 + @types/react 18.3.28
23:20:02.040 + @types/react-dom 18.3.7
23:20:02.040 + @vitejs/plugin-react 4.7.0
23:20:02.040 + autoprefixer 10.5.0
23:20:02.040 + cssnano 7.1.7
23:20:02.040 + encoding 0.1.13
23:20:02.040 + eslint 9.39.4
23:20:02.040 + eslint-config-next 15.5.15
23:20:02.040 + firebase-admin 12.7.0
23:20:02.040 + husky 9.1.7
23:20:02.040 + jsdom 25.0.1
23:20:02.040 + lint-staged 15.5.2
23:20:02.040 + postcss 8.5.10
23:20:02.040 + postcss-flexbugs-fixes 5.0.2
23:20:02.040 + postcss-focus-visible 8.0.2
23:20:02.041 + postcss-import 16.1.1
23:20:02.041 + postcss-preset-env 10.6.1
23:20:02.041 + postcss-reporter 7.1.0
23:20:02.041 + prettier 3.8.3
23:20:02.041 + prettier-plugin-tailwindcss 0.6.14
23:20:02.041 + rimraf 6.1.3
23:20:02.041 + tailwindcss 3.4.19
23:20:02.041 + tailwindcss-animate 1.0.7
23:20:02.041 + typescript 5.9.3
23:20:02.041 + vite 6.4.2
23:20:02.041 + vitest 3.2.4
23:20:02.041 
23:20:02.098 
23:20:02.098 > airanh-app@1.0.0 prepare /vercel/path0
23:20:02.099 > husky
23:20:02.099 
23:20:02.169 Done in 14.8s
23:20:02.222 Detected Next.js version: 15.5.15
23:20:02.269 Running "pnpm run build"
23:20:03.079 
23:20:03.079 > airanh-app@1.0.0 build /vercel/path0
23:20:03.080 > next build
23:20:03.080 
23:20:03.711 Attention: Next.js now collects completely anonymous telemetry regarding usage.
23:20:03.712 This information is used to shape Next.js' roadmap and prioritize features.
23:20:03.712 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
23:20:03.712 https://nextjs.org/telemetry
23:20:03.712 
23:20:03.791    ▲ Next.js 15.5.15
23:20:03.791    - Environments: .env.local
23:20:03.791    - Experiments (use with caution):
23:20:03.791      · serverActions
23:20:03.791      · webVitalsAttribution
23:20:03.791      · optimizePackageImports
23:20:03.791 
23:20:03.904    Creating an optimized production build ...
23:20:23.025  ✓ Compiled successfully in 18.8s
23:20:23.029    Linting and checking validity of types ...
23:20:26.973 
23:20:26.973 ./app/chat/page.tsx
23:20:26.974 279:19  Warning: img elements must have an alt prop, either with meaningful text, or an empty string for decorative images.  jsx-a11y/alt-text
23:20:26.974 316:13  Warning: img elements must have an alt prop, either with meaningful text, or an empty string for decorative images.  jsx-a11y/alt-text
23:20:26.974 
23:20:26.974 info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/app/api-reference/config/eslint#disabling-rules
23:20:30.700    Collecting page data ...
23:20:31.134 unhandledRejection ReferenceError: self is not defined
23:20:31.134     at Object.<anonymous> (.next/server/vendors.js:1:1)
23:20:31.135     at __webpack_require__.f.require (.next/server/webpack-runtime.js:247:28)
23:20:31.135     at <unknown> (.next/server/webpack-runtime.js:174:40) {
23:20:31.135   type: 'ReferenceError'
23:20:31.135 }
23:20:31.190  ELIFECYCLE  Command failed with exit code 1.
23:20:31.218 Error: Command "pnpm run build" exited with 1